apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryu-core
  namespace: ryu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryu-core
  template:
    metadata:
      labels:
        app: ryu-core
    spec:
      nodeSelector:
        kubernetes.io/hostname: nodo-k3s-maestro
      containers:
        - name: ryu-core
          image: docker.io/arturoalvarez/ryu-core:1.0
          command: ["ryu-manager"]
          args:
            [
              "--observe-links",
              "ryu.app.simple_switch_13",
              "ryu.app.ofctl_rest",
              "ryu.app.gui_topology.gui_topology",
              "--ofp-tcp-listen-port", "6633",
              "--wsapi-host", "0.0.0.0",
              "--wsapi-port", "8080"
            ]
          ports:
            - containerPort: 6633
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ryu-core-svc
  namespace: ryu
spec:
  type: NodePort
  selector:
    app: ryu-core
  ports:
    - name: openflow
      port: 6633
      targetPort: 6633
      nodePort: 30266
    - name: internal-api
      port: 8080
      targetPort: 8080
      nodePort: 31699
