apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryu-rest
  namespace: ryu
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ryu-rest
  template:
    metadata:
      labels:
        app: ryu-rest
    spec:
      containers:
        - name: ryu-rest
          image: docker.io/arturoalvarez/ryu-rest:4.0
          command: ["ryu-manager"]
          args: ["ryu.app.ofctl_rest", "--wsapi-host", "0.0.0.0", "--wsapi-port", "8080"]
          env:
            - name: RYU_CORE_URL
              value: "http://ryu-core-svc:8080"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ryu-rest-lb
  namespace: ryu
spec:
  type: LoadBalancer
  selector:
    app: ryu-rest
  ports:
    - name: rest
      port: 8080
      targetPort: 8080
