apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryu-gui
  namespace: ryu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryu-gui
  template:
    metadata:
      labels:
        app: ryu-gui
    spec:
      containers:
        - name: ryu-gui
          image: docker.io/arturoalvarez/ryu-gui:1.0
          command: ["ryu-manager"]
          args:
            [
              "ryu.app.gui_topology.gui_topology",
              "--wsapi-host", "0.0.0.0",
              "--wsapi-port", "8080"
            ]
          env:
            - name: RYU_CORE_URL
              value: "http://ryu-core-svc:8080"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ryu-gui-lb
  namespace: ryu
spec:
  type: LoadBalancer
  selector:
    app: ryu-gui
  ports:
    - port: 8080
      targetPort: 8080
