apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryu-core
  namespace: ryu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ryu-core
  template:
    metadata:
      labels:
        app: ryu-core
    spec:
      containers:
        - name: ryu-core
          image: docker.io/arturoalvarez/ryu-core:1.0
          command: ["ryu-manager"]
          args:
            [
              "--observe-links",
              "ryu.app.simple_switch_13",
              "ryu.app.topology.switches",
              "--ofp-tcp-listen-port", "6633"
            ]
          ports:
            - containerPort: 6633
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ryu-core-svc
  namespace: ryu
spec:
  selector:
    app: ryu-core
  ports:
    - name: openflow
      port: 6633
      targetPort: 6633
    - name: internal-api
      port: 8080
      targetPort: 8080
  clusterIP: 10.43.200.10  # puedes omitirlo si quieres que sea asignado autom√°ticamente
